### ISSUE TITLE
Language Bindings Chapter RC Review

### ISSUE THREAD

**Issue by wesbland** [mpi-forum/mpi-issues#332]
# Problem

These are reported by @whit-schonbein:

In [pdf](https://www.mpi-forum.org/docs/drafts/mpi-2020-draft-report.pdf) pages (absolute/relative):

* [x] p. 834/794, line 13: "feature" --> "features"
* [x] p. 835/795, line 45: "recomended" --> "recommended"
* [x] p. 840/800, lime 10: "a INTEGER" --> "an INTEGER"
* [x] p. 840/800, line 44: Remove newline before "(End of advice to users)".
* [x] p. 844/804, line 5: "2's complement" --> "two's complement" (for consistency with the other two places the term appears)
* [ ] p. 851/811, line 14: "type" --> "types"

Comments from @abouteiller:

* [x] pdf 938, A.3.11, pp898:39
  * MPI_Status_set_elements_x, shouldn’t it be set_elements_c??? 
* [x] pdf 951, A4, pp911:20,30
  * Missing variants KIND=MPI_COUNT_KIND for MPI_Isendrecv and MPI_Isendrecv_replace
* [x] pdf 954-955, A.4, pp914:41, pp915:5
  * Same for MPI_Sendrecv and MPI_Sendrecv_replace
* [x] pdf 958, A.4.3, pp918:32
  * Needs verification: MPI_Get_elements_x and MPI_Get_elements present, both using MPI_COUNT_KIND. Is this normal? 
* [x] pdf 962, A.4, pp922:18
  * Needs verification:
  * MPI_Type_create_struct: count,  array_of_blocklenghts(count) and array_of_diplacements(count) are all type MPI_COUNT_KIND. I believe array_of_displacements should be MPI_ADDRESS_KIND.
  * Same issue for MPI_Type_create_subarray pp922:41, array_of_sstarts(dims) should be MPI_ADDRESS_KIND?
* [X] I noticed that some `_c` functions are not listed close-by the corresponding procedure. 
  * These appear to be in alphabetical order though, so maybe its ok>? Listing some examples here. There are more in the following pages, but I’ll stop reporting until we decide if this is a problem or not. 
  * These are not a problem.  Functions listed alphabetically within a section.
* [X] pdf 939, A.3.12, pp899:28,34,42,45
* [X] pdf 940, A.3.12, pp900:5,11,20,22
  * Inconsistent ordering for functions MPI_File_iread_at, iread_at_c, iread_c; the `_c` variant should be moved close-by its non `_c` variant. 
  * Same issue with iwrite_c, iwrite_at_c
  * No, this is correct as is.  The routines are listed, correctly, alphabetically within a section.
* [X] pdf 936-937, A.3 pp896:33 ; pp897:4
  * MPI_Rget_c is not close-by MPI_Rget, block pp897:4-8 should be moved at pp896:38
  * No, this is correct as is.  The routines are listed, correctly, alphabetically within a section.

Additional comments from @hmt23:

* [x] page 1067 in the pdf and 1027 in the document page number:
  * Line 14 : The label of B.1 points to Annex B instead of B.1
  * Line 20 : Same as before, the label of Annex B.2 points to Annex B instead of B.2.

From @hritzdorf:

* [x] Page Number 848, Page 888, Line 31-32; New predefined error handler MPI_ERRORS_ABORT is missing

From @jjhursey:

I finished my review of PDF pages Pages 885-910. Below are my notes listing first the PDF page then the document page, in case that helps. There are a number of inconsistencies that seem like the pythonization should help resolve, but someone would need to take a closer look to see for sure.

* [x] p 886/846: MPI_ERR_SESSION missing from Error classes listing.
* [x] p 886/846: MPI_ERR_VALUE_TOO_LARGE missing from Error classes listing.
* [no] p 885-886/845-846: Tables 9.1 and 9.2 are alphabetized, whereas the tables in this chapter are not. Could we use the same python technique to generate this table to keep them consistent? [Sorry, too late, may go to MPI-4.1]
* [x] p 888/848: MPI_ERRORS_ABORT is missing from the "Error-handling specifiers" list
* [no] p 890/850 (Line 17-26): Should the table for "Name Predefined Datatypes" to "C++ types" be removed? [No, these predefined datatype handles support native C++ types that do not have a corresponding type in C. C++ is supported in MPI (since MPI-2.2) by the C binding plus the types in this table.]
* [x] p 892/852 (Line 38-39): Missing " or TYPE(MPI_Session)" for Fotran 2008 binding (see MPI_SESSION_FINALIZE signature).
* [no] p 895/855: MPI_COMBINER_HINDEXED_INTEGER missing from "Datatype Decoding Constants" [REMOVED from MPI-3.0]
* [no] p 895/855: MPI_COMBINER_HVECTOR_INTEGER missing from "Datatype Decoding Constants" [REMOVED from MPI-3.0]
* [no] p 895/855: MPI_COMBINER_INDEXED_INTEGER missing from "Datatype Decoding Constants" [DOES NOT EXIST]
* [no] p 895/855: MPI_COMBINER_STRUCT_INTEGER missing from "Datatype Decoding Constants" [REMOVED from MPI-3.0]
* [x] p 889/859 (Line 39-48): Typeface for the "MPI_T interface" is different than the other types in this subsection.
* [x] p 901/861 (Line 28-48): Spacing after the last four functions is inconsistent with the other declarations on the page - single vs double spacing.
* [x] p 905/865 (Line 13): The "SUBROUTINE" line should be shifted to the left margin to match the other declarations on the page.
* [x] p 905/865 (Line 45): There seems to be an extra space here (inconsistent with other sets of declarations). If this space is removed it is possible that the final line of the "SESSION_DELETE_ATTR_FUNCTION" moves from the top of the next page to the bottom of this page.
* [x] p 907/867 (Subsection A.1.5): Missing "argv"
* [x] p 908/868 (Subsection A.1.5): Missing "command"
* [x] p 908/868 (Subsection A.1.5): Missing "maxprocs"
* [x] p 908/868 (Subsection A.1.5, Line 18): "mpi_assert_strict_start_ordering" is no longer defined in the standard. It should be removed.
* [x] p 908/868 (Subsection A.1.5): Missing "mpi_size"
* [N/A] p 908/868 (Subsection A.1.5): Missing "mpi_thread_support_level" [There is only a "thread_level"]
* [x] p 908/868 (Subsection A.1.5, Line 21): "mpi_optimization_goal" is no longer defined in the standard. It should be removed.
* [x] p 908/868 (Subsection A.1.5, Line 22): Missing "mpi_reuse_count" is no longer defined in the standard. It should be removed.
* [x] p 908/868 (Subsection A.1.5): Missing "thread_level"
* [x] p 908/868 (Subsection A.1.5): Missing "wdir"
* [x] p 908/868 (Subsection A.1.6): Missing "MPI_THREAD_FUNNELED"
* [x] p 908/868 (Subsection A.1.6): Missing "MPI_THREAD_MULTIPLE"
* [x] p 908/868 (Subsection A.1.6): Missing "MPI_THREAD_SERIALIZED"
* [x] p 908/868 (Subsection A.1.6): Missing "MPI_THREAD_SINGLE"
* [x] p 908/868 (Subsection A.1.6): Should we include "mpi://WORLD", "mpi://SELF" (from section 11.3.2) and a note about the "mpi://" namespace? Probably as a new table. [DONE in new table A.1.5]
* [ ] p 908/868 (Subsection A.1.6): Should we include "native", "internal", and "external32" values for datarep in MPI_FILE_SET_VIEW? Probably as a new table.

From @RolfRabenseifner 

* [ ] p 1107/1067 (Constant Index): MPI_COMM_PARENT on page 417/377 is together with MPI_COMM_WORLD and MPI_COMM_SELF are strings and
  * [ ] should be listed there as strings
  * [ ] and should also be added in a new table in Annex A.1. May be that A.1.5 is changed to "Asorted Strings" or so and may then also include the table proposed above on "native", "internal", and "external32".

**Comment by wesbland** [comment]
Added additional comments by @abouteiller

**Comment by wesbland** [comment]
Additional comments from @hmt23:

* page 1067 in the pdf and 1027 in the document page number:
    - Line 14 : The label of B.1 points to Annex B instead of B.1
    - Line 20 : Same as before, the label of Annex B.2 points to Annex B instead of B.2.

**Comment by wgropp** [comment]
The reference to page 1067 is incorrect above - it is a (ghastly) error on page 1031/PDF page 1071.  Fixed in PR https://github.com/mpi-forum/mpi-standard/pull/346

**Comment by wgropp** [comment]
Fixed
p. 835/795, line 45: "recomended" --> "recommended"
p. 840/800, lime 10: "a INTEGER" --> "an INTEGER"
p. 840/800, line 44: Remove newline before "(End of advice to users)".
p. 844/804, line 5: "2's complement" --> "two's complement" (for consistency with the other two places the term appears)

in PR 349

**Comment by hritzdorf** [comment]
Page Number 848, Page 888, Line 31-32; New predefined error handler MPI_ERRORS_ABORT is missing

**Comment by wgropp** [comment]
The routines in Annex A are sorted alphabetically within each section - the _c versions will often but not always follow the "regular" version.  (Rget_accumulate comes after Rget but before Rget_c, for example). We could do a different ordering, but I don't see the value in that - this annex is of limited value in any case, since it simply duplicates data already presented.

**Comment by jjhursey** [comment]
I finished my review of PDF pages Pages 885-910. Below are my notes listing first the PDF page then the document page, in case that helps.  There are a number of inconsistencies that seem like the pythonization should help resolve, but someone would need to take a closer look to see for sure.

----

 * p 886/846: MPI_ERR_SESSION missing from Error classes listing.
 * p 886/846: MPI_ERR_VALUE_TOO_LARGE missing from Error classes listing.
 * p 885-886/845-846: Tables 9.1 and 9.2 are alphabetized, whereas the tables in this chapter are not. Could we use the same python technique to generate this table to keep them consistent?
 * p 888/848: MPI_ERRORS_ABORT is missing from the "Error-handling specifiers" list
 * p 890/850 (Line 17-26): Should the table for "Name Predefined Datatypes" to "C++ types" be removed?
 * p 892/852 (Line 38-39): Missing " or TYPE(MPI_Session)" for Fotran 2008 binding (see MPI_SESSION_FINALIZE signature).
 * p 895/855: MPI_COMBINER_HINDEXED_INTEGER missing from "Datatype Decoding Constants"
 * p 895/855: MPI_COMBINER_HVECTOR_INTEGER missing from "Datatype Decoding Constants"
 * p 895/855: MPI_COMBINER_INDEXED_INTEGER missing from "Datatype Decoding Constants"
 * p 895/855: MPI_COMBINER_STRUCT_INTEGER missing from "Datatype Decoding Constants"
 * p 889/859 (Line 39-48): Typeface for the "MPI_T interface" is different than the other types in this subsection.
 * p 901/861 (Line 28-48): Spacing after the last four functions is inconsistent with the other declarations on the page - single vs double spacing.
 * p 905/865 (Line 13): The "SUBROUTINE" line should be shifted to the left margin to match the other declarations on the page.
 * p 905/865 (Line 45): There seems to be an extra space here (inconsistent with other sets of declarations). If this space is removed it is possible that the final line of the "SESSION_DELETE_ATTR_FUNCTION" moves from the top of the next page to the bottom of this page.
 * p 907/867 (Subsection A.1.5): Missing "argv"
 * p 908/868 (Subsection A.1.5): Missing "command"
 * p 908/868 (Subsection A.1.5): Missing "maxprocs"
 * p 908/868 (Subsection A.1.5, Line 18): "mpi_assert_strict_start_ordering" is no longer defined in the standard. It should be removed.
 * p 908/868 (Subsection A.1.5): Missing "mpi_size"
 * p 908/868 (Subsection A.1.5): Missing "mpi_thread_support_level"
 * p 908/868 (Subsection A.1.5, Line 21): "mpi_optimization_goal" is no longer defined in the standard. It should be removed.
 * p 908/868 (Subsection A.1.5, Line 22): Missing "mpi_reuse_count" is no longer defined in the standard. It should be removed.
 * p 908/868 (Subsection A.1.5): Missing "thread_level"
 * p 908/868 (Subsection A.1.5): Missing "wdir"
 * p 908/868 (Subsection A.1.6): Missing "MPI_THREAD_FUNNELED"
 * p 908/868 (Subsection A.1.6): Missing "MPI_THREAD_MULTIPLE"
 * p 908/868 (Subsection A.1.6): Missing "MPI_THREAD_SERIALIZED"
 * p 908/868 (Subsection A.1.6): Missing "MPI_THREAD_SINGLE"
 * p 908/868 (Subsection A.1.6): Should we include "mpi://WORLD", "mpi://SELF" (from section 11.3.2) and a note about the "mpi://" namespace? Probably as a new table.
 * p 908/868 (Subsection A.1.6): Should we include "native", "internal", and "external32" values for datarep in MPI_FILE_SET_VIEW? Probably as a new table.

**Comment by wesbland** [comment]
I combined all of the comments back up into the issue description. I'd recommend that things get checked off of that list as they are fixed to make it easy to track when everything is done.

**Comment by wesbland** [comment]
@puribangalore Is everything here addressed in a PR? Even if it's not merged.

**Comment by puribangalore** [comment]
The version in the rc branch with hash 948fcf8 contains all the items that have a checkmark. All unchecked items are not fixed, majority of them are related to Annex A.

@RolfRabenseifner Which PR addresses the issues related to Annex A listed above?

**Comment by RolfRabenseifner** [comment]
@jjhursey and @hritzdorf I never saw the reported bugs in Annex A.1 because I never looked at this issue because it reported in its title that it is about Chapter 19. If somebody would have directly contacted me, that would have been helpful. Too many github emails in my email account.

@wgropp I'll try to fix these about 30 bugs in Annex A latest this American night / European Friday morning - I hope that this is still without delaying the FRM. I'll check parts now.

**Comment by RolfRabenseifner** [comment]
@wgropp Dear Bill, PR405 is now redy to be merged. All is done. The remaining issues may go to MPI-4.1. Best regards, Rolf

**Comment by wgropp** [comment]
PR405 was merged on Dec 9th (see https://github.com/mpi-forum/mpi-standard/pull/405 ). Did you mean a different PR?

**Comment by puribangalore** [comment]
I believe it is PR504 - https://github.com/mpi-forum/mpi-standard/pull/504.

**Comment by RolfRabenseifner** [comment]
Final issues of this Issue #332 are resolved when PR506 https://github.com/mpi-forum/mpi-standard/pull/506 is merged.

**Comment by RolfRabenseifner** [comment]
@wgropp Dear Bill, please can you merge PR506 https://github.com/mpi-forum/mpi-standard/pull/506. Best regards, Rolf

**Comment by wgropp** [comment]
PR 506 is merged.  Can this be closed?

**Comment by puribangalore** [comment]
Yes, this can be closed now.
