### ISSUE TITLE
MPI_Psend_init_c & MPI_Precv_init_c

### ISSUE THREAD

**Issue by cniethammer** [mpi-forum/mpi-issues#765]
# Problem

The bindings of `MPI_Psend_init` and `MPI_Precv_init`  do not follow the naming scheme of procedures taking `MPI_Count` arguments / misses a regular int version.

Note: check examples for correct usage and argument declarations!

# Proposal

As discussed in the Forum meeting 14/09/2023: Make it consistent and have an integer and a embiggened  (_c) version.

Note: Check other places in the standard for more issues of this kind.

# Changes to the Text

Rename the current `MPI_P(send|recv)_init` to `MPI_P(send|recv)_c` and add another binding for `MPI_P(send|recv)_init` that uses an `int count`|`INTEGER count` 

# Impact on Implementations

# References and Pull Requests
https://github.com/mpi-forum/mpi-standard/pull/888

**Comment by cniethammer** [comment]
Just realized that the Fortran binding used `INTEGER(KIND=MPI_COUNT_KIND)`. Should this be changed back to pure `INTEGER` and reflect the bindings of regular send operations?

@martinruefenacht Is there a way to generate regular+'_c' bingings for C and F08 but `MPI_COUNT_KIND` ones for Fortran?

**Comment by jprotze** [comment]
The function has this signature since MPI-4.0. The proposed change breaks the API. 
Why didn't 4.0 replace all `int count` by `MPI_Count count` in the first place?

**Comment by jeffhammond** [comment]
This breaks API for approximately zero users.  The reason we didn't change ALL the APIs for large count is that would have broken every MPI code in existence.

**Comment by jeffhammond** [comment]
Breaking backwards compatibility for non-existent users is a very bad reason for not fixing an obvious mistake in the standard.  This issue describes an inconsistency relative to all other features that has multiple negative effects on users.  Fixing this will ensure once this feature has users, they are satisfied.

**Comment by cniethammer** [comment]
Note: this PR will change the old Fortran module interface from `INTEGER(KIND=MPI_COUNT_KIND)` to `INTEGER` without a replacement - however there are no other old Fortran module interfaces and users of MPI_Count should anyway use mpi_f08, already.

**Comment by raffenet** [comment]
What are the negative effects on users with the current interface?

**Comment by jprotze** [comment]
To clarify my aversion:

Implementing PMPI tools, we try to maintain compatibility with whatever MPI implementation the user has available.
To provide this compatibility, we already have enough extra work dealing with inconsistent implementations of const arguments, missing PMPI functions, or incomplete sessions support. Breaking the API after 2 years enforces implementations to put just another thing on this pile of annoyance.

If you need a reference for a code using the current interface of these functions:
The MUST 1.9 release from May implements checks for partitioned communication and relies on the specified API.

PS: If the forum decides to implement this change anyways, we are "happy" to add this on our list of implementation inconsistencies that require a work-around.

**Comment by jeffhammond** [comment]
> What are the negative effects on users with the current interface?

Who are the current users?

I'm an RMA user, using it in production for over a decade. If the forum changes the API in a backwards incompatible way with an erratum, it would not be even 10% as bad as dealing with the defective implementations I've worked around over the years. 

My point is, user pain must be measured carefully. If the only users today are experts, they can deal with this. And it's worth it if it makes the API cleaner for when the unwashed masses get around to using it in 5 or 10 years.

**Comment by raffenet** [comment]
Psend/Precv_init are control path functions and the count argument is pass-by-value. What are we trying to fix? Is there any scenario where `MPI_Count` would not be able to hold any value representable by `int`?

**Comment by jeffhammond** [comment]
Fortran does not have integer size promotion. There's an issue already related to MPI window constructor that illustrates the unpleasant user experience that results. https://github.com/mpi-forum/mpi-issues/issues/528

If MPI_Count is 128b, this interface may be problematic if it forces the use of 128b integers internally for partitioned communication on devices where 128b integers are very expensive. 

But most important of all, this API deviates from all the others. It's inconsistent and hard to use. One must know that this API and it alone does not follow the large count API design pattern.

This is like Reduce_scatter(_block) except we can fix it without affecting more than a handful of expert users.

**Comment by jprotze** [comment]
I don't get the 128b on device argument. Do you expect these API functions to be called on a device that doesn't support 128b integers? If it's expensive, so what? This is supposed to be one-time cost during init.

I can accept the Fortran argument. Also the argument for a consistent API.

**Comment by raffenet** [comment]
> Fortran does not have integer size promotion. There's an issue already related to MPI window constructor that illustrates the unpleasant user experience that results. #528

This makes sense. But can it be solved in the F08 binding without breaking the C API/ABI?

> 
> If MPI_Count is 128b, this interface may be problematic if it forces the use of 128b integers internally for partitioned communication on devices where 128b integers are very expensive.

We can internally store the count value in whatever the most appropriate type is, so I don't think this is a concern.

**Comment by cniethammer** [comment]
I'd like to add some more points to the discussion to support the errata:

1.) A reader of the text for Large Count support in MPI looking at Chapter 19.2 will find the following at the beginning after getting introduced to the general problem of too small integer types for count arguments:
> ... In order to avoid breaking backwards compatibility, this version of MPI supports larger
types via separate additional MPI procedures in C (suffixed with “_c”) and via interface
polymorphism in Fortran ... (Followed by exceptions)

If this is not a general rule and newer MPI 4.0+ functions should not have an integer interface at all the text should mention this early to prevent any confusion about this - and so everybody is prepared to check the MPI history for the point in time a function was introduced.

2.) MPI_Psend_init uses in the old Fortran module interface definition `count INTEGER(KIND=MPI_CONT_KIND)`, however you find in 19.2.
> In older Fortran bindings (mpif.h (deprecated) and use mpi), no new interfaces and
no new specific procedures for larger types are provided beyond what existed in MPI-3.1;
all MPI procedures have the same types as in the versions prior to MPI-4.0.

Which I interpret as follows: no (old) Fortran module interface should support `MPI_Count`.
Especially, MPI_Send, MPI_Send_init, ... do not have `MPI_Count` support - and therefore the MPI_Psend_init Fortran interface with `INTEGER(KIND=MPI_COUNT_KIND)` should not be there at all as it is inconsistent with the existing interfaces.

What are implementations doing here? adding MPI_Count support to the full mpif.h and (old) mpi module?

3.) Who wants to teach MPI to students when they come just from their "how to do good interface design" class and have to explain them "MPI_Count is supported by all '_c'-postfixed functions ... with the following exeptions since MPI 4.0: ..."
or
"MPI_Count is supported by all functions today - however the original MPI send and recv procedures with around 300 other old functions need an '_c'"

I would argue we should address this now as uptake is practically non existing in applications so far and as teaching material just starts to exist.

**Comment by raffenet** [comment]
> I'd like to add some more points to the discussion to support the errata:
> 
> 1.) A reader of the text for Large Count support in MPI looking at Chapter 19.2 will find the following at the beginning after getting introduced to the general problem of too small integer types for count arguments:
> 
> > ... In order to avoid breaking backwards compatibility, this version of MPI supports larger
> > types via separate additional MPI procedures in C (suffixed with “_c”) and via interface
> > polymorphism in Fortran ... (Followed by exceptions)
> 
> If this is not a general rule and newer MPI 4.0+ functions should not have an integer interface at all the text should mention this early to prevent any confusion about this - and so everybody is prepared to check the MPI history for the point in time a function was introduced.

I agree it is important we establish a convention.

> 2.) MPI_Psend_init uses in the old Fortran module interface definition `count INTEGER(KIND=MPI_CONT_KIND)`, however you find in 19.2.
> 
> > In older Fortran bindings (mpif.h (deprecated) and use mpi), no new interfaces and
> > no new specific procedures for larger types are provided beyond what existed in MPI-3.1;
> > all MPI procedures have the same types as in the versions prior to MPI-4.0.
> 
> Which I interpret as follows: no (old) Fortran module interface should support `MPI_Count`. Especially, MPI_Send, MPI_Send_init, ... do not have `MPI_Count` support - and therefore the MPI_Psend_init Fortran interface with `INTEGER(KIND=MPI_COUNT_KIND)` should not be there at all as it is inconsistent with the existing interfaces.
> 
> What are implementations doing here? adding MPI_Count support to the full mpif.h and (old) mpi module?

No `_c` functions were added to mpif.h or the mpi module in MPICH. `MPI_Psend_init` and `MPI_Precv_init` are implemented in `mpi.mod` as specified in MPI-4.0 with `INTEGER(KIND=MPI_COUNT_KIND) :: count`. `mpi.mod` also supports `INTEGER(KIND=MPI_COUNT_KIND)` arguments to `_x` functions defined prior to MPI-4.0.

> 
> 3.) Who wants to teach MPI to students when they come just from their "how to do good interface design" class and have to explain them "MPI_Count is supported by all '_c'-postfixed functions ... with the following exeptions since MPI 4.0: ..." or "MPI_Count is supported by all functions today - however the original MPI send and recv procedures with around 300 other old functions need an '_c'"
> 
> I would argue we should address this now as uptake is practically non existing in applications so far and as teaching material just starts to exist.

Agreed. Since I wasn't in the room I wanted to understand how the discussion led to this proposal. Thanks for the additional context.

What we have to consider on our side is whether this change would be an ABI break for MPICH. We _could_ say it's not and insist that there are no real users, but I expect distro packagers would still raise an eyebrow.

**Comment by Wee-Free-Scot** [comment]
This change is being handled as an errata to MPI-4.0, which will first appear in the MPI-4.1 version of the standard document, but will be listed in the errata that must be applied against the MPI-4.0 standard document.

Thus, it was never wrong. Your memories of once seeing that the interfaces didn't have "int" versions is a spill-over from an erased timeline that never really happened. MPI-3.1 did not have these procedures, MPI-4.0 (plus errata) has them in their correct polykind form, and MPI-4.1 has them in exactly the same form as MPI-4.0 (plus errata) with no changes. There is no spoon/break of compatibility.

**Comment by jprotze** [comment]
I'm glad that you managed to find a way to clean up the history without breaking applications compiled against older MPICH-4 releases and running with newer MPICH-4 releases. 

As this ABI breaking change is guaranteed to break in so many ways, I can only recommend application programmers to wait adopting this new API until when mpich-4 reached end of life time including the use in derived MPI implementations. Debugging this ABI break will be hard, as it will not be visible by just looking at the binary library.

**Comment by mahermanns** [comment]
I am a bit torn between both sides of the argument.

As a tool provider myself, I would count ourselves to the expert side of the MPI user community (see @jeffhammond 's [comment](https://github.com/mpi-forum/mpi-issues/issues/765#issuecomment-1719958115)), and just as Joachim said, we are a bit used to working around to peculiarities of individual versions of MPI implementations. I agree to @jprotze that this, at times, can be annoying, but at least for Score-P we would have infrastructure from prior quirks in implementations to cope with this in a reasonable manner. So I would not put a lot of weight on this argument. Just as MUST, also Score-P recently added support for partitioned communication (although it's not released yet), and while working on this support it was not easy to find many applications to actually use this in practice, which feeds into @jeffhammond's  assessment, that usage "out there" is currently pretty scarce. 

However, as far as I understand, the issue here is also that this might be a problem for providers of binary distributions of their tools (Matlab, etc.?) in the future, relying on the ABI compatibility of the underlying MPI implementation to work on different systems. This may lead to hard to detect issues for users of those tools (when 'pre-change' MPI implementations are present and the incompatibility is not detected), and we should carefully check how the proposed API change would affect specifically those users of MPI. Then again, such tools could define a specific base implementation (that uses the fixed API definition) as part of a compatibility statement and be done with it, no?

As an educator, I fully support the desire to have a consistent interface (especially with all the discussions of semantics in the past years, about blocking vs. non-blocking and local vs. non-local, and how a user might get an intuition about behavior from the name of the function itself). So having an API that indicates an `MPI_Count` argument by having an `_c` suffix would help users here, especially non-experts. It will be easier to teach and to understand.

So my personal weighing of arguments would currently be something like
1. ABI compatibility support aspects (it's clear that we break something, question is whether this is a deal-breaker for implementations and current users)
2. Cleanliness of interface (the whole teaching and understanding aspect)
3. Personal pain in trying to support implementations that already implemented this with the "to-be wrong" interface.

@Wee-Free-Scot 's argument with the "Back-to-the-future"-esque alternate timeline where this never existed is more of a technicallity. For me, it would just mean, yes, we are formally allowed to go down this path. Whether we *should* go down this path is what we discuss here, right?

As we may actually not have a "significant number of users" of the API we might actually sneak past  [Hyrum's Law](https://www.hyrumslaw.com/). So what we have to discuss is "what means significant" (1, 10, 100 users? Single user where this costs them $X?) and whether we have crossed this threshold.

**Comment by jeffhammond** [comment]
If Matlab, for example, does not use a function, does it have an ABI dependency on that function?  I don't think so, but I'm not absolutely certain.  If not, then we go back to the prior argument, which is, does anyone use this function?  I'm skeptical that Matlab is using the latest MPI features, for a variety of reasons, not the least of which is their lack of universal implementation.  Given the implementation status in Open MPI, I find it very surprising that anybody is arguing that there is a large user base for anything introduced in MPI 4.0 or later, given that Open MPI is the default MPI in all the Linux distributions (much to my chagrin, but that's another matter).  They have started implementing partitioned but it appears to not work until the 5.0.x release branch, which isn't shipping.

**Comment by jeffhammond** [comment]
Also, I'll note there is precedent for break API and ABI in these functions in existing implementations: https://github.com/open-mpi/ompi/issues/9534 😄

**Comment by mahermanns** [comment]
> Also, I'll note there is precedent for break API and ABI in these functions in existing implementations: [open-mpi/ompi#9534](https://github.com/open-mpi/ompi/issues/9534) 😄

But that is the master branch, not a release, right?

**Comment by jeffhammond** [comment]
Sure, you can choose between (1) there has been an API/ABI break and (2) these functions aren't even implemented in the most widely distributed MPI implementation.  Either choice indicates a lack of ecosystem impact from this erratum.

**Comment by mahermanns** [comment]
I am not arguing against this ... I am generally supporting changing this in the proposed way and that it would be a nice thing to have (clean and intuitive interface for users, better to teach, etc.) ... it's just that I have zero experience in the kind of ABI contracts that implementations like MPICH and Open-MPI might have with downstream MPI vendors and whether there might be penal damages involved for such ABI changes.

**Comment by cniethammer** [comment]
From Open MPI side there should not be much of an impact, IMHO: Partitioned P2P has not been included in the current versions so far and will be introduced with the 5.0 series - which is not finalized yet and only release candidates are around for testing.

**Comment by jsquyres** [comment]
Can I ask what is the specific *problem* that is being addressed by this issue?

The MPI Forum Procedures version 3.4 in section 2.2.3 defines Errata Proposals as:

> Errata proposals for the MPI Standard Documents are usually “small” and deal with “critical” changes to documents to correct errors, clarify egregious ambiguities, etc.

* This proposal is small: yes (at least: it's a small textual change -- but arguably, it's a large semantic change)
* This proposal is critical: no
* This proposal corrects an error: maybe -- you could argue either way
* This proposal clarifies an egregious ambiguity: arguably, no

I agree that this proposal tidies up a minor error.  But what is the *problem*?

The Forum is potentially creating an ABI break -- and breaking an existing MPI implementation -- to tidy up a minor error.

Do we really want to set a precedent to break ABI to tidy up a small error?

**Comment by jeffhammond** [comment]
It's critical for Fortran. The 4.0 definition is not consistent with how every other API works and is not usable without memorizing the exception, because Fortran doesn't have integer promotion.

Fixing this in Fortran is also trivial in the polymorphic case. Users never see it, it just works the way it is supposed to.

**Comment by jeffhammond** [comment]
MPI has no ABI so there is no ABI break. This will force MPICH to deal with its ABI contract with users. We should not confuse the two.

**Comment by jsquyres** [comment]
I agree that the MPI-4.0 definition is not tidy -- it's different than all the other APIs, etc.  But it's not a technical *problem*, per se.  It's perfectly usable as it is.

That being said, fixing the `mpi_f08` module does not create an ABI problem, so I have no problem with that.

But breaking `mpif.h` and the `mpi` module and the C bindings ABI just because something is untidy -- that's... dangerous.

And yes, I know that MPI currently has no ABI.  But the implementations do, and it's proven to be so important that the Forum is undertaking an ABI effort for future versions of the standard.  You can't say "ABI is not important" when you're the chair of the ABI subcommittee.  😉

**Comment by jeffhammond** [comment]
mpif.h is deprecated and therefore not a factor here. 

We could add polymorphism in mpi.mod to solve this. It's not a problem in practice, it's just a big change this late. We could do it here as a bandaid and then add the whole set in 4.2.

**Comment by jeffhammond** [comment]
ABI is extremely important but the way to address it is with a standard ABI not by treating implementation issues as an ABI problem for the Forum. Right now, we have an API problem and we need to fix the API. Then we can solve ABI. But having a broken API here isn't helping anything with the ABI.

**Comment by jsquyres** [comment]
You're arguing apples and oranges.

* Until MPI-4.1 passes, `mpif.h` is not deprecated.
* If you want to add polymorphism in the `mpi` module to fix this problem there, then you're making this API different in a *different* way than all the others (there is no `INTEGER` / `INTEGER(KIND=MPI_COUNT_KIND)` polymorphism elsewhere in the `mpi` module).
    * I.e., you're saying that it's ok for some APIs to be different than others, but only in some ways and not others.  That's... weird.
* Breaking the C ABI can't be taken lightly, even if it's "only an issue for the implementations".
    * The precedent here for breaking an ABI just for being "untidy" creates a massive loophole for the future.
    * Don't forget that this breaks ABI in just about the worst way possible, too: you're potentially changing the size of a parameter.  This could create pretty terrible bugs that could be really hard to track down.
* There is no API problem.  The MPI-4.0 APIs are perfectly usable as they are defined.
    * Yes, it's (potentially) annoying for Fortran users who have to explicitly convert.  Or they could just use MPI_COUNT for everything, and not have to convert.
    * But again: the APIs are perfectly functional exactly as they are.
* "But having a broken API here isn't helping anything with the ABI" -- I don't understand how the this issue creates a technical problem for the MPI Forum ABI effort.  Can you explain?

**Comment by jeffhammond** [comment]
"Just use MPI_Count for everything" - what release of Open MPI supports all of large count? Or even large count for the 25 most used functions?

**Comment by jsquyres** [comment]
You're still arguing apples and oranges.

You first said that implementations weren't important and we should fix the standard, but now you're challenging an implementation issue as a defense for your position.

Which is it?  You can't argue both.

**Comment by schulzm** [comment]
This seems like an issue that is probably easier discussed on a TelCon than through a lengthy thread here - I will suggest a virtual meeting on this topic.

**Comment by jeffhammond** [comment]
> You're still arguing apples and oranges.
> 
> 
> 
> You first said that implementations weren't important and we should fix the standard, but now you're challenging an implementation issue as a defense for your position.
> 
> 
> 
> Which is it?  You can't argue both.

I'm saying that your argument that Fortran users should just use large count everywhere is not credible given the implementation with which you are affiliated still does not support those features.

I'm allowed to make this argument regardless of anything else I've said. You told Fortran users to solve the problem by doing something that you know does not work, unless you also intend to argue that Fortran users should only use MPICH from now on too.

When Open MPI releases support for all large count features in the Fortran bindings, we can revisit your argument.

**Comment by wesbland** [comment]
After much discussion in the virtual meeting on 2023-10-11, we decided to remove these changes from MPI 4.1 and not propose an errata to 4.0.

For MPI 4.2, there should be a proposal that adds `MPI_PSEND_INIT_C` (same as proposal here), `MPI_PSEND_INIT_I` (integer version), `MPI_PRECV_INIT_C`, and `MPI_PRECV_INIT_I`. This will both provide a consistent `_C` interface and preserve backward compatibility.

https://github.com/mpi-forum/mpi-standard/pull/932 will revert the changes in MPI 4.1 from this issue and the backward compatibility issue that went with it.
